apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: project-pipeline-demo-operator
rules:
- apiGroups:
  - project.openshift.io
  resources:
  - projects
  verbs:
  - '*'
- apiGroups:
  - authorization.openshift.io
  resources:
  - rolebindings
  verbs:
  - '*'
- apiGroups:
  - cop.redhat.com
  resources:
  - '*'
  verbs:
  - '*'
